### ISSUE TITLE
bleak bluezdbus client.py:168: RuntimeWarning: coroutine 'Communicator._handle_disconnect' was never awaited

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [greghope667/square-off-remote#1]
Hello, 

first of all: Thank you. Second: Let me join the 'avoid the square off app' party :-)

Currently, I understand that 'python3 game.py' should start a stockfish versus random-move game. Unfortunately I get random errors from time to time as below and I could not find anything in the internet, looks like a random disconnection? Any hints are welcome. Thank you. 

`python3 game.py 
Searching for device...
Found device, connecting...
Connected
Connected, battery =  2-90
*
e2e4
f7f6
d2d4
b7b5
f1b5
h7h6
d1h5
.../square-off-remote/venv/lib64/python3.11/site-packages/bleak/backends/bluezdbus/client.py:168: RuntimeWarning: coroutine 'Communicator._handle_disconnect' was never awaited
  self._disconnected_callback()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback`

**Comment by greghope667** [comment]
Hi, thanks for the comment and feedback. It's always nice to hear when someone is using my code :)

> Second: Let me join the 'avoid the square off app' party :-)

Agreed. I really like the hardware but find the app kind of annoying to deal with. If only Square Off would give us some an API for control rather than having to hack around with my dodgy code...

> `python3 game.py  Searching for device... Found device, connecting... Connected Connected, battery =  2-90 * e2e4 f7f6 d2d4 b7b5 f1b5 h7h6 d1h5 `

This bit looks correct, is the board moving ok here?

> `.../square-off-remote/venv/lib64/python3.11/site-packages/bleak/backends/bluezdbus/client.py:168: RuntimeWarning: coroutine 'Communicator._handle_disconnect' was never awaited self._disconnected_callback() RuntimeWarning: Enable tracemalloc to get the object allocation traceback`

I think this error message is a bug in my own code - I'm handling async+threads wrong (I don't understand python async very well). The message occurs for me, too, whenever the program exits. Someday I'll get round to fixing this bug but I doubt it's the cause of your issues.

If the game isn't ending normally (i.e. draw/checkmate) then it's likely there's a bluetooth issue like a disconnect or message timeout occurring. My board works ok but maybe you have a slightly different model or firmware?

One easy thing to try is setting `debug` to `True` in Communicator.py, this should print all transmit/receive messages to the console which might indicate if the comms are getting stuck somewhere.

**Comment by eqikkwkp25-cyber** [comment]
Hello, 

cant reproduce it anymore during games. Its present at the end of each game, yes. Nevertheless, I set the debug flag to "True" within communicator.py to catch the issue in future. 

I got my board since more or less two days:-) Though i am not a programmer i can read code, test and document things. 

Your to do list within the readme and the priority there matches my initial goals by far. On my potential square off project list i have: 

- opening the board and check if i can reduce the mechanical noise (my seems to be too noisy compared to some others shown on Youtube)  
- replace my PC setup with a raspberry pi one: pi zero 2 w + battery + RC + mic + loudspeakers + epaper touch, its a small unit, main goal here: a FEN puzzle a day using the realtime clock wakeup
- replace pocketsphinx with a modern STTs (though pocketsphinx with a restricted grammar should do the job, played with it about a decade ago)
- replacing the stockfish AI with an online AI, for instance Lichess maia bot
- ...

I guess you can close this issue. Maybe it is a good idea to open something like a discussion thread within this github repository if there is a feature like that.

Again: Thanks for sharing the current code. It is for sure a cool "magical" project.

**Comment by greghope667** [comment]
Your ideas look good. I've created a discussion thread https://github.com/greghope667/square-off-remote/discussions/3 for future ideas as well

**Comment by eqikkwkp25-cyber** [comment]
Solved by commit [Fix disconnection handling ](https://github.com/greghope667/square-off-remote/commit/929a4ead2416d2d848c834aa65bb4c25e568d25f)
